[build]
builder = "nixpacks"
buildCommand = "uv pip install -e .[cpu]"

[deploy]
startCommand = "uvicorn api.src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
USE_GPU = "false"
USE_ONNX = "false"
PYTHONPATH = "/app:/app/api"
MODEL_DIR = "src/models"
VOICES_DIR = "src/voices/v1_0"
WEB_PLAYER_PATH = "/app/web" 